// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phfelpgvwxhxyxflbngp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoZmVscGd2d3hoeHl4ZmxibmdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTI5NjYsImV4cCI6MjA2NTEyODk2Nn0.dFOeCMUfbvyPSkmxFvbqgEUh9L4d4zZZ9TsWTh2LtmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);